'use strict';
/*
 * gen-deploy.js — DEPLOY.md : ইন্টারনেটে তোলা + Play Store পর্যন্ত
 *
 * ⚠️ এই ফাইলের সবচেয়ে জরুরি অংশ উপরের "RULES CHANGE" বাক্সটা।
 *    হোস্টিং আর Play Store-এর নিয়ম প্রতি কয়েক মাসে বদলায়। তাই এখানে
 *    ধাপগুলোর সাথে সাথে লেখা আছে — কোথায় গিয়ে যাচাই করতে হবে, আর
 *    AI-কে ঠিক কোন প্রশ্নটা করলে আজকের নিয়ম জানা যাবে।
 *
 *    তথ্য যাচাই করা হয়েছে : সেপ্টেম্বর ২০২৬
 */

const VERIFIED = 'September 2026';

var store = require('./gen-store.js');

function deployMd(app, BRAND, codeStr) {
  var PKG = store.pkgName(app || {});
  app = app || {};
  BRAND = BRAND || {};
  var num  = String(app.num || '0000');
  var name = String(app.name || 'App');
  var C    = codeStr || 'PKG-0000-APP';

  var L = [];
  var P = function () {
    for (var i = 0; i < arguments.length; i++) {
      if (arguments[i] !== null && arguments[i] !== undefined) L.push(arguments[i]);
    }
  };

  /* ─────────── HEAD ─────────── */
  P('# DEPLOY — put ' + name + ' online, and on the Play Store',
    '',
    '**Package code: `' + C + '`**  ·  APP ' + num,
    '',
    'This continues from `AI-HELP.md`. Finish **STEP 1–10** there first — the app',
    'must run on your own computer before any of this makes sense.',
    '',
    'यह `AI-HELP.md` के आगे का हिस्सा है. पहले वहाँ **STEP 1–10** पूरे कीजिए —',
    'app आपके अपने कंप्यूटर पर चले, तभी यह सब काम का है.',
    '',
    '---',
    '');

  /* ─────────── RULES CHANGE — সবচেয়ে জরুরি ─────────── */
  P('## ⚠️ READ THIS FIRST — these rules change  /  पहले यह पढ़िए',
    '',
    'Everything below was **checked in ' + VERIFIED + '**. Hosting platforms and Google',
    'change their prices, free limits, page layouts and rules every few months.',
    '**Some of what follows will be out of date by the time you read it.**',
    '',
    'That is normal and it is not a problem — as long as you **check before you follow.**',
    '',
    'नीचे सब कुछ **' + VERIFIED + '** में जाँचा गया था. Hosting कंपनियाँ और Google अपने',
    'दाम, मुफ़्त सीमाएँ, पन्नों की बनावट और नियम हर कुछ महीनों में बदलते रहते हैं.',
    '**इसलिए कुछ बातें आपके पढ़ते समय पुरानी हो चुकी होंगी.** यह सामान्य है —',
    'बस **करने से पहले जाँच लीजिए.**',
    '',
    '### Ask an AI to check today\'s rules  /  आज के नियम AI से पूछिए',
    '',
    'Paste this into any AI **that can search the web** (Claude, ChatGPT, Gemini,',
    'Perplexity), attach `AI-HELP.md`, and put the STEP number you are on:',
    '',
    '```',
    'Search the web and tell me today\'s rules, then compare with what my guide says.',
    '',
    'I am on STEP <number> of DEPLOY.md (package ' + C + ').',
    'My guide was written in ' + VERIFIED + ' and says:',
    '    <paste the step you are about to do>',
    '',
    'Please check and tell me:',
    '  1. Is this still correct today?',
    '  2. What changed — prices, free limits, button names, page layout?',
    '  3. What exactly should I do instead, step by step?',
    '  4. Give me the official documentation link so I can confirm.',
    '```',
    '',
    '**हिंदी में भी यही भेज सकते हैं** — ऊपर का ढाँचा वैसा रखिए, अपनी बात हिंदी में लिखिए.',
    '',
    '### Always trust these over this guide  /  इन पर भरोसा कीजिए, इस गाइड पर नहीं',
    '',
    '| What | Official source — the only thing that is never out of date |',
    '|---|---|',
    '| Play Store rules | https://support.google.com/googleplay/android-developer |',
    '| Play Console itself | https://play.google.com/console |',
    '| Play fees & account | Play Console Help → "Get started with Play Console" |',
    '| Expo / building the app | https://docs.expo.dev |',
    '| Expo prices & free limits | https://expo.dev/pricing |',
    '| Render hosting | https://render.com/docs |',
    '| Render prices & free limits | https://render.com/pricing |',
    '| GitHub | https://docs.github.com |',
    '',
    '**The page in front of you always wins over the page in this guide.**',
    'If a button has a different name, it was renamed — look for the nearest match,',
    'or ask the AI with a screenshot.',
    '',
    '**आपकी स्क्रीन पर जो दिख रहा है, वही सही है.** बटन का नाम अलग हो तो समझिए',
    'नाम बदल गया है — मिलता-जुलता बटन ढूँढिए, या स्क्रीनशॉट के साथ AI से पूछिए.',
    '',
    '### If you want to watch a video  /  अगर वीडियो देखना हो',
    '',
    'Search YouTube and **sort by upload date, then pick something from the last few',
    'months.** An old video on this topic is worse than no video.',
    '',
    '```',
    'deploy node express app to render 2026',
    'expo eas build android aab tutorial 2026',
    'google play console closed testing 12 testers 2026',
    '```',
    '',
    'YouTube पर खोजिए और **"Upload date" से छाँटिए — पिछले कुछ महीनों का वीडियो',
    'ही देखिए.** इस विषय पर पुराना वीडियो, न देखने से भी बुरा है.',
    '',
    '---',
    '');

  /* ─────────── COST ─────────── */
  P('## 💰 WHAT IT COSTS AND HOW LONG IT TAKES',
    '',
    'Honest numbers, ' + VERIFIED + '. **Verify each one before you pay anything.**',
    '',
    '| | Money | Time |',
    '|---|---|---|',
    '| Run it on your own computer | free | done already |',
    '| Server online, hobby use | free tier, with limits below | ~1 hour |',
    '| Server truly always-on | paid plan, small monthly fee | same |',
    '| App file (.aab / .apk) for your phone | free tier build service | ~1 hour |',
    '| Play Store developer account | **$25, one time, never renews** | 1–2 hours |',
    '| Identity verification by Google | free | **2–5 days** |',
    '| 12 testers for 14 continuous days | free, but you must find people | **14+ days** |',
    '| Google reviews your app | free | days to weeks |',
    '',
    '> **From today to "live on the Play Store" is realistically 3–6 weeks**, and almost',
    '> all of it is waiting, not working. Start the account and verification early.',
    '>',
    '> **आज से Play Store तक असल में ३–६ हफ़्ते लगते हैं**, और उसका ज़्यादातर हिस्सा',
    '> इंतज़ार है, काम नहीं. इसलिए account और verification सबसे पहले शुरू कीजिए.',
    '',
    '---',
    '');

  /* ─────────── WHICH PATH ─────────── */
  P('## 🔀 FIRST, FIND OUT WHICH PATH YOU ARE ON',
    '',
    'Run this inside your app folder:',
    '```',
    'node -e "var p=require(\'./package.json\');console.log(((p.dependencies||{}).expo)?\'EXPO\':\'BARE\')"',
    '```',
    '✅ **`EXPO`** → follow PART B as written. This is the easy path.',
    '✅ **`BARE`** → PART A is the same, but PART B needs Android Studio instead of the',
    '   build service. Give this file to an AI and ask for the bare React Native route.',
    '',
    'हिंदी: `EXPO` आए तो नीचे सब वैसा ही कीजिए. `BARE` आए तो PART A वही है, पर',
    'PART B के लिए AI से "bare React Native" वाला रास्ता पूछिए.',
    '',
    '---',
    '');

  /* ─────────── PART A ─────────── */
  P('# PART A — put the server online  /  server को इंटरनेट पर लाना',
    '',
    'Right now your server only runs while your own computer is on. These steps put it',
    'on the internet so the app works from anywhere.',
    '',
    'अभी server सिर्फ़ तभी चलता है जब आपका कंप्यूटर चालू हो. ये steps उसे इंटरनेट पर',
    'ले आएँगे, ताकि app कहीं से भी चले.',
    '',

    '### STEP 11 — Make a GitHub account',
    'Go to **https://github.com** and sign up. Free.',
    '✅ **You should see:** your own page at `github.com/<your-username>`.',
    '> Your code has to live somewhere the hosting service can read it. GitHub is that place.',
    'हिंदी: github.com पर मुफ़्त account बनाइए. आपका अपना पन्ना खुलना चाहिए.',
    '',

    '### STEP 12 — Install Git',
    'Download from **https://git-scm.com/downloads**, install, then **close and reopen**',
    'your terminal and run:',
    '```',
    'git --version',
    '```',
    '✅ **You should see:** a version number, e.g. `git version 2.46.0`',
    '❌ `not recognized` → the terminal was open before you installed. Close it, open again.',
    'हिंदी: नंबर दिखना चाहिए. न दिखे तो terminal बंद करके दोबारा खोलिए.',
    '',

    '### STEP 13 — Put your code on GitHub',
    'On GitHub click **New repository**, give it a name, choose **Private**, and create it',
    'with **no** README or .gitignore. Then in your app folder:',
    '```',
    'git init',
    'git add .',
    'git commit -m "first"',
    'git branch -M main',
    'git remote add origin <the URL GitHub showed you>',
    'git push -u origin main',
    '```',
    '✅ **You should see:** your files on the GitHub page after you refresh it.',
    '❌ Asked for a password → GitHub no longer accepts account passwords here. It will',
    '   normally open a browser window to sign in; if not, ask the AI for the current',
    '   sign-in method — this is one of the things that changes.',
    '> 🔒 **Check that `.env` is NOT on GitHub.** `.gitignore` should have kept it out.',
    '>    If you can see it there, delete the repository and ask the AI before continuing.',
    '> 🔒 **देखिए कि `.env` GitHub पर न गया हो.** दिख जाए तो repository हटा दीजिए और',
    '>    आगे बढ़ने से पहले AI से पूछिए.',
    '',

    '### STEP 14 — Create the hosting service',
    'Go to **https://render.com**, sign up with GitHub, then **New → Web Service** and',
    'pick your repository. Settings to use:',
    '',
    '| Field | Value |',
    '|---|---|',
    '| Build command | `npm install` |',
    '| Start command | `node server/index.js` |',
    '| Instance type | Free |',
    '',
    '✅ **You should see:** the build log runs, then the status turns **Live**, and you get',
    '   a URL ending in `.onrender.com`. **Copy that URL.**',
    '❌ Build fails → open the log, copy the **last 20 lines**, and send them as STEP 14.',
    'हिंदी: status **Live** होना चाहिए और एक URL मिलना चाहिए. वो URL copy कर लीजिए.',
    '',
    '> ⚠️ **What "free" means here** (' + VERIFIED + ', confirm at render.com/pricing):',
    '> a free service **goes to sleep after about 15 minutes with no visitors**, and the',
    '> next visitor waits **about a minute** while it wakes up. There is also a monthly',
    '> pool of free hours. **This is fine for showing people. It is not 24×7.**',
    '> A small paid plan removes the sleeping. Free databases also expire — check the',
    '> current terms before you put anything real in one.',
    '>',
    '> ⚠️ **यहाँ "मुफ़्त" का मतलब:** कोई न आए तो service **लगभग 15 मिनट में सो जाती है**,',
    '> और अगले आदमी को जगने तक **लगभग एक मिनट** रुकना पड़ता है. **दिखाने के लिए ठीक है,**',
    '> **24×7 नहीं.** छोटा paid plan लेने पर यह सोना बंद हो जाता है.',
    '',

    '### STEP 15 — Give the server its secrets',
    'Open your service → **Environment** → add every line from your `.env` file, one by one,',
    'as name and value. Save. The service restarts on its own.',
    '✅ **You should see:** status back to **Live** after the restart.',
    '> Your `.env` is deliberately not on GitHub, so the server has no other way to get these.',
    'हिंदी: `.env` की हर लाइन यहाँ name–value के रूप में डालिए. फिर status **Live** होना चाहिए.',
    '',

    '### STEP 16 — Check the live server is answering',
    'On your own computer (put your own `.onrender.com` URL in):',
    '```',
    'node -e "require(\'https\').get(\'https://YOUR-APP.onrender.com\',function(r){console.log(\'REPLY\',r.statusCode)}).on(\'error\',function(e){console.log(\'NO REPLY\',e.code)})"',
    '```',
    '✅ **You should see:** `REPLY` and any number. Any reply means it is alive.',
    '⚠️ If it was asleep, the **first** try can fail or take about a minute. **Try twice.**',
    '❌ Still `NO REPLY` after two tries → open Render\'s **Logs** tab, copy the last lines,',
    '   send as STEP 16.',
    'हिंदी: `REPLY` आना चाहिए. सोया हुआ हो तो पहली बार में देर लगती है — **दो बार कोशिश कीजिए.**',
    '',

    '### STEP 17 — Point the app at the live server',
    'Open `config.js` and replace the local address with your `https://...onrender.com` URL.',
    'Then:',
    '```',
    'node --check config.js',
    '```',
    '✅ **You should see: nothing.** Then open the app — it should load **without your own**',
    '   **server running.** That is the whole point of PART A.',
    '❌ Blank screen → the address is wrong. It must start with `https://` and have **no**',
    '   slash at the end.',
    'हिंदी: अब app आपके अपने server के बिना चलना चाहिए. सफ़ेद स्क्रीन आए तो पता गलत है —',
    '`https://` से शुरू, और अंत में slash नहीं.',
    '',
    '> 🎉 **PART A done.** Your app now works from any phone, anywhere.',
    '> 🎉 **PART A पूरा.** अब app किसी भी फ़ोन से, कहीं से भी चलेगा.',
    '',
    '---',
    '');

  /* ─────────── PART B ─────────── */
  P('# PART B — on to the Play Store  /  Play Store तक',
    '',
    '> ⚠️ **Google changes these rules often, and changed them recently.** Before you pay',
    '> the fee, run the "check today\'s rules" question from the top of this file.',
    '>',
    '> ⚠️ **Google ये नियम अक्सर बदलता है, और हाल ही में बदले हैं.** फ़ीस देने से पहले',
    '> ऊपर वाला "आज के नियम" सवाल ज़रूर पूछिए.',
    '',

    '### STEP 18 — Make it yours  ⚠️ the most important step here',
    '',
    'Open **`app.json`** and change two things:',
    '',
    '**1. The package name.** Find `"package"` and `"bundleIdentifier"`. Both say:',
    '```',
    '"' + PKG + '"',
    '```',
    'Replace **`yourname`** with your own name or website, no spaces or capitals:',
    '```',
    '"' + PKG.replace('yourname', 'rahulsharma') + '"',
    '```',
    '⚠️ **This must be unique in the whole world.** Thousands of people have this same',
    'package. If you leave `yourname`, you will collide with them and Google will reject it.',
    '',
    '**2. The app name.** Find `"name"` and make it yours.',
    '',
    'Then make the icon:',
    '```',
    'node make-icon.js',
    '```',
    '✅ **You should see:** two `OK` lines, and an `assets` folder with `icon.png` in it.',
    'Open it — a pattern in your app\'s colour, unique to this app. **Want your own picture?**',
    'Replace both files with your own 1024×1024 PNG.',
    '',
    'Now check you did step 1 properly:',
    '```',
    'node -e "var a=require(\'./app.json\').expo.android.package;console.log(a, a.indexOf(\'yourname\')<0?\'OK\':\'<-- STILL SAYS yourname, FIX IT\')"',
    '```',
    '✅ **You should see:** your package name and `OK`.',
    'हिंदी: `app.json` में `yourname` की जगह अपना नाम लिखिए — **यह दुनिया में अनोखा होना',
    'ज़रूरी है.** फिर `node make-icon.js` चलाइए. जाँच में `OK` आना चाहिए.',
    '',

    '### STEP 19 — Install the build tool',
    'Make a free account at **https://expo.dev**, then:',
    '```',
    'npm install -g eas-cli',
    'eas --version',
    'eas login',
    '```',
    '✅ **You should see:** a version number, then your username after logging in.',
    '> This builds the app file in the cloud, so you do not need Android Studio.',
    '> `eas.json` is already in your folder, so there is nothing to configure.',
    '> Free-tier build allowances exist and change — check **expo.dev/pricing**.',
    'हिंदी: version नंबर और फिर आपका username दिखना चाहिए. `eas.json` पहले से मौजूद है.',
    '',

    '### STEP 20 — Build a test file for your own phone',
    'The `preview` profile is already set up to give you an `.apk`:',
    '```',
    'eas build -p android --profile preview',
    '```',
    '✅ **You should see:** a link to watch the build, and when it finishes, a **download**',
    '   **link for an `.apk` file**. Builds usually take 10–25 minutes.',
    '❌ Build fails → open the link, find the **first red error**, copy it, send as STEP 20.',
    '> An `.apk` installs directly on a phone. An `.aab` (STEP 23) is only for the Play Store.',
    'हिंदी: `.apk` फ़ाइल का download link मिलना चाहिए. `.apk` सीधे फ़ोन में लगती है.',
    '',

    '### STEP 21 — Try it on a real phone',
    'Download the `.apk` on an Android phone and open it. Allow installing from this source',
    'when asked.',
    '✅ **You should see:** your app installed like any other app, opening to its first screen.',
    '❌ Opens and closes at once → send a screenshot and say STEP 21. Usually the server',
    '   address from STEP 17.',
    '> **Do not skip this.** Fixing things now is free. Fixing them after Google\'s review',
    '> costs you days.',
    '> **यह मत छोड़िए.** अभी सुधारना मुफ़्त है; Google की जाँच के बाद सुधारने में दिन लगते हैं.',
    '',

    '### STEP 22 — Open the Play Console account  ⚠️ start this early',
    'Go to **https://play.google.com/console**. Before you begin, **turn on 2-Step**',
    '**Verification** on your Google account. Keep a government ID ready.',
    '',
    'As of ' + VERIFIED + ' — **confirm all of this on the official page**:',
    '',
    '- **$25, paid once**, by credit or debit card. No yearly renewal. Non-refundable.',
    '- You choose **Personal** or **Organization** at signup. **Read the next step before**',
    '  **choosing** — the choice decides how hard publishing will be.',
    '- **Google verifies your identity.** Expect **2–5 days**. You can prepare your listing',
    '  meanwhile, but you cannot publish until it clears.',
    '- Your name, your card and your ID must **match**. Mismatches are the usual reason',
    '  verification fails, and the fee does not come back.',
    '',
    '✅ **You should see:** the Play Console dashboard, and a verification status you can watch.',
    'हिंदी: पहले Google account पर **2-Step Verification** चालू कीजिए, सरकारी ID तैयार रखिए.',
    'फ़ीस **$25, एक बार**. पहचान की जाँच में **२–५ दिन** लगते हैं. नाम, card और ID एक जैसे हों.',
    '',

    '### STEP 23 — Personal or Organization? — this one matters most',
    '',
    'As of ' + VERIFIED + ', **confirm on the official page before deciding**:',
    '',
    '| | Personal account | Organization account |',
    '|---|---|---|',
    '| Who it is for | one individual | a registered business |',
    '| Extra document | government ID | business details incl. a D-U-N-S number |',
    '| Getting that document | you have it | free to request, **can take weeks** |',
    '| **12 testers for 14 days** | **required** | Google documents this against personal accounts |',
    '',
    '**Personal accounts created after 13 November 2023** cannot publish publicly until a',
    '**closed test has run with at least 12 testers, opted in continuously for 14 days.**',
    'Then you apply for production access, and Google reviews that application.',
    '',
    '> You can move from Personal to Organization later, but **not the other way**.',
    '> Most people making their first app should take **Personal** and accept the 14 days.',
    '>',
    '> Personal से Organization में बाद में जा सकते हैं, **उल्टा नहीं**. पहली app बनाने वाले',
    '> ज़्यादातर लोगों के लिए **Personal** ही ठीक है — 14 दिन का इंतज़ार मान लीजिए.',
    '',

    '### STEP 24 — Build the Play Store file',
    '```',
    'eas build -p android --profile production',
    '```',
    '✅ **You should see:** a download link for an **`.aab`** file this time, not `.apk`.',
    '> New apps must be uploaded to Google as `.aab`. Google makes the `.apk` for each',
    '> phone itself. That is why STEP 20 and this step produce different files.',
    'हिंदी: इस बार **`.aab`** फ़ाइल मिलेगी. नई apps Google को `.aab` में ही देनी होती हैं.',
    '',

    '### STEP 25 — Create the app listing',
    '',
    '> 📄 **Open `STORE-LISTING.md`** — every field Play Console asks for is prepared there,',
    '> with what to write and what to change. **Open `PRIVACY.md`** for the privacy policy.',
    '>',
    '> 📄 **`STORE-LISTING.md` खोलिए** — Play Console के हर खाने का जवाब वहाँ तैयार है.',
    '> Privacy policy के लिए **`PRIVACY.md`** खोलिए.',
    '',
    'In Play Console: **Create app**. Then fill in the store listing. You will need:',
    '',
    '- App name, short description, full description',
    '- **App icon** 512×512 PNG',
    '- **Feature graphic** 1024×500',
    '- **At least 2 phone screenshots** — take them from your own phone in STEP 21',
    '- **A privacy policy URL** — a public web page. This is **required**, not optional.',
    '',
    '✅ **You should see:** each section turn from incomplete to complete.',
    '> `PRIVACY.md` is a ready template — fill in the `[...]` parts and put it on a public',
    '> page. Ask an AI for the simplest free way to host one page if you are unsure.',
    '> ⚠️ **Do not paste the listing text unchanged** — thousands have the same file, and',
    '> identical listings get treated as spam. Rewrite it in your own words.',
    'हिंदी: icon, graphic, कम से कम २ screenshots, और एक **privacy policy का लिंक** चाहिए —',
    'यह ज़रूरी है. न हो तो AI से लिखवा लीजिए और मुफ़्त में कहीं डाल दीजिए.',
    '',

    '### STEP 26 — Answer Google\'s forms',
    'Fill in **Data safety**, **content rating**, **target audience**, **ads** and the other',
    'declarations Play Console asks for.',
    '✅ **You should see:** the dashboard checklist filling up.',
    '> ⚠️ **Answer truthfully.** Wrong answers here get apps removed later, sometimes after',
    '> they are already published. If you are unsure what your app collects, ask the AI with',
    '> `AI-HELP.md` attached — the file map tells it what your server stores.',
    '> ⚠️ **सच-सच भरिए.** ग़लत जवाब बाद में app हटवा देते हैं. पक्का न हो तो `AI-HELP.md`',
    '> लगाकर AI से पूछिए — उसमें लिखा है कि आपका server क्या-क्या रखता है.',
    '',

    '### STEP 27 — Upload to closed testing',
    'Go to **Testing → Closed testing**, create a track, upload your `.aab`, and add your',
    'testers\' Gmail addresses. Share the opt-in link Google gives you.',
    '✅ **You should see:** the release live on that track, and an opt-in link you can send.',
    '> **Recruit 15–18 people, not 12.** Some will drop out, and dropping below 12 restarts',
    '> the clock. Ask friends, family, classmates, a group chat.',
    '> **12 नहीं, 15–18 लोग जोड़िए.** कुछ लोग निकल जाते हैं, और 12 से नीचे जाते ही',
    '> 14 दिन की गिनती फिर से शुरू हो जाती है.',
    '',

    '### STEP 28 — Wait 14 days  ⏳',
    'The testers must stay opted in **continuously**. Google also looks at whether they',
    'actually used the app, so ask them to open it a few times.',
    '✅ **You should see:** the tester count in Play Console staying at 12 or above, every day.',
    '❌ It drops below 12 → add more people **immediately**, before the streak breaks.',
    '> There is no way around this wait for a personal account. Use the two weeks to',
    '> collect feedback and fix things.',
    '> Personal account के लिए इस इंतज़ार से बचने का कोई रास्ता नहीं. इन दो हफ़्तों में',
    '> feedback लीजिए और कमियाँ ठीक कीजिए.',
    '',

    '### STEP 29 — Apply for production access',
    'After 14 clean days, Play Console lets you **apply for production access**. You answer',
    'questions about your testing and how ready the app is.',
    '✅ **You should see:** the application submitted, then a decision from Google.',
    '⏳ Review commonly takes about a week, sometimes longer.',
    '❌ Rejected → the reason is written in the message. Paste the whole message to the AI',
    '   with `AI-HELP.md` and say STEP 29.',
    'हिंदी: 14 साफ़ दिनों के बाद production access के लिए apply कीजिए. मना हो जाए तो पूरा',
    'संदेश AI को दिखाइए.',
    '',

    '### STEP 30 — Publish, and then keep it alive',
    'Once production access is granted, create a production release with your `.aab` and roll',
    'it out.',
    '✅ **You should see:** your app on the Play Store. 🎉',
    '',
    '**After that, three things keep it alive:**',
    '',
    '1. **Updates** — every new upload needs a higher version code than the last, or Google',
    '   refuses it. In an Expo project this is set in your app config.',
    '2. **The server** — if it is on a free plan it still sleeps. Real users on the Play',
    '   Store are the point at which a small paid plan stops being optional.',
    '3. **Google\'s deadlines** — Google requires apps to be rebuilt against newer Android',
    '   versions periodically, and will stop showing apps that fall behind. **Check the',
    '   current target API deadline once a year.**',
    '',
    'हिंदी: **१.** हर update में version code बढ़ाना ज़रूरी है. **२.** असली users आने पर',
    'मुफ़्त server का सोना अब ठीक नहीं — छोटा paid plan ले लीजिए. **३.** Google समय-समय पर',
    'नए Android के हिसाब से app दोबारा बनाने को कहता है — साल में एक बार जाँच लीजिए.',
    '',
    '---',
    '');

  /* ─────────── ASK ─────────── */
  P('## 🆘 STUCK ON ANY STEP',
    '',
    'Attach **`AI-HELP.md`** and **`DEPLOY.md`**, add a screenshot, and send:',
    '',
    '```',
    'APP ' + num + '  ·  ' + C,
    'STEP: <number>',
    '',
    'My guide was written in ' + VERIFIED + '. Please search the web and check',
    'whether this step has changed before you answer.',
    '',
    'What I did:      <...>',
    'Expected:        <paste the "✅ You should see" line>',
    'What I got:      <paste output, or see screenshot>',
    '```',
    '',
    '**हिंदी में भी यही भेजिए** — बस अपनी बात हिंदी में लिख दीजिए.',
    '',
    'The two sentences about searching the web matter more than anything else you write.',
    'They turn a guess into a checked answer.',
    '',
    '**वेब पर जाँचने वाली वो दो लाइनें सबसे ज़रूरी हैं** — उन्हीं से अंदाज़ा जाँचे हुए जवाब में बदलता है.',
    '');

  if (BRAND.youtube) P('', '---', '', 'More sets and walkthroughs / और sets: ' + BRAND.youtube, '');
  P('', '`' + C + '`  ·  APP ' + num + '  ·  guide written ' + VERIFIED, '');

  return L.join('\n');
}

module.exports = { deployMd, VERIFIED };
